### ISSUE TITLE
Error during build  in Pi "smart-lock pi build-toolchain"

### ISSUE THREAD

**Issue by rgkrishnas** [OpenDDS/opendds-smart-lock#9]
Hi,
I am trying to install in Raspberry pi 4 and end-up with the below error, could you please help us to fix this issue during installation?
$ smart-lock pi build-toolchain
....
In file included from /home/pi/pi-opendds/build/target/dds/DCPS/CoherentChangeControl.h:79:0,
                 from /home/pi/pi-opendds/build/target/dds/DCPS/WriterInfo.h:17,
                 from /home/pi/pi-opendds/build/target/dds/DCPS/WriterInfo.cpp:11:
/home/pi/pi-opendds/build/target/dds/DCPS/CoherentChangeControl.inl: In constructor 'OpenDDS::DCPS::WriterCoherentSample::WriterCoherentSample(ACE_UINT32, OpenDDS::DCPS::SequenceNumber)':
/home/pi/pi-opendds/build/target/dds/DCPS/CoherentChangeControl.inl:16:1: note: parameter passing for argument of type 'OpenDDS::DCPS::SequenceNumber' will change in GCC 7.1
 WriterCoherentSample::WriterCoherentSample (
 ^~~~~~~~~~~~~~~~~~~~
arm-linux-gnueabihf-g++ -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -ggdb -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE   -I/home/pi/pi-opendds/build/target/ACE_TAO/ACE -D__ACE_INLINE__ -I/home/pi/pi-opendds/build/target/ACE_TAO/ACE -I/home/pi/pi-opendds/build/target/ACE_TAO/TAO -I.. -I../dds -DOPENDDS_SECURITY -DNOMINMAX -DOPENDDS_DCPS_BUILD_DLL  -c -fPIC -o .shobj/DCPS/debug.o /home/pi/pi-opendds/build/target/dds/DCPS/debug.cpp
arm-linux-gnueabihf-g++ -fvisibility=hidden -fvisibility-inlines-hidden -Wnon-virtual-dtor -ggdb -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE   -I/home/pi/pi-opendds/build/target/ACE_TAO/ACE -D__ACE_INLINE__ -I/home/pi/pi-opendds/build/target/ACE_TAO/ACE -I/home/pi/pi-opendds/build/target/ACE_TAO/TAO -I.. -I../dds -DOPENDDS_SECURITY -DNOMINMAX -DOPENDDS_DCPS_BUILD_DLL  -c -fPIC -o .shobj/DCPS/security/framework/SecurityConfig.o /home/pi/pi-opendds/build/target/dds/DCPS/security/framework/SecurityConfig.cpp
Assembler messages:
Fatal error: can't create .shobj/DCPS/security/framework/SecurityConfig.o: No such file or directory
make[2]: *** [.shobj/DCPS/security/framework/SecurityConfig.o] Error 2
/home/pi/pi-opendds/build/target/ACE_TAO/ACE/include/makeinclude/rules.local.GNU:189: recipe for target '.shobj/DCPS/security/framework/SecurityConfig.o' failed
make[2]: Leaving directory '/home/pi/pi-opendds/build/target/dds'
make[1]: *** [OpenDDS_Dcps] Error 2
GNUmakefile.dist:464: recipe for target 'OpenDDS_Dcps' failed
make[1]: Leaving directory '/home/pi/pi-opendds/build/target'
GNUmakefile:3: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c cd pi-opendds &&   ./configure --prefix=${OPENDDS_PREFIX}     --ace-github-latest     --security --no-tests --target=linux-cross     --target-compiler=arm-linux-gnueabihf-g++     --openssl=${BUILD_ROOT}/pi-openssl/usr/local     --xerces3=${BUILD_ROOT}/pi-xerces &&   make -j${OPENDDS_MAKE_JOBS}' returned a non-zero code: 2

**Comment by mitza-oci** [comment]
> Fatal error: can't create .shobj/DCPS/security/framework/SecurityConfig.o: No such file or directory

Do any of those intermediate directories exist?
Is there free space on the filesystem?
